# Generated by Django 4.2.2 on 2023-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('hmname', models.CharField(max_length=100)),
                ('typee', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_school',
            },
        ),
    ]
